### ISSUE TITLE
Footer - Criar todo conteúdo do banner final.

### ISSUE THREAD

**Issue by TalysonSoares** [AlekGDEV/avaliacao-react#13]
- [x] Adicionar informação de oferta especial.
- [x] Adicionar título e texto.
- [x] Criar um botão de "ver oferta".
